# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master  # Declenche le pipeline a chaque modification sur la branche 'master'.

pool: 'default' # Definit le pool d'agents par defaut pour executer les taches.

steps: 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Abonnement Azure PAYG(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'tpfinal'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\projetfinal\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\projetfinal\azuredeploy.parameters.json'
    deploymentMode: 'Incremental'